name: ASP.NET Core 7.0 Example build and deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # 添加workflow_dispatch事件以手動觸發

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build package
        run: |
          cd github_actions
          dotnet build --configuration Release --no-restore
          dotnet publish -c Release -r linux-x64 --self-contained false -o deploy  
      - name: Debug
        run: |
          cd /home/runner/work/github_actions/github_actions/github_actions/deploy/
          pwd  # 打印当前工作目录
          ls   # 列出当前目录内容     
          
      - name: Upload package to remote server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |       
            echo "Working Directory: $(pwd)"
            ls -la
            #cd ./work/github_actions/github_actions/github_actions/deploy/
            #scp -i ${{ secrets.SSH_PRIVATE_KEY }} -P 22 -r ./ ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/home/project/example/

