name: ASP.NET Core 7.0 Example build and deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # 添加workflow_dispatch事件以手動觸發

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build package
        run: |
          cd github_actions
          dotnet build --configuration Release --no-restore
          dotnet publish -c Release -r linux-x64 --self-contained false -o deploy                        
      - name: Create Deployment Package
        run: zip -r deploy-package.zip ./deploy

      - name: Debug Info
        run: |
          pwd
          ls -l
  
      - name: Upload to Remote Server
        run: |
          echo "${{secrets.SSH_PRIVATE_KEY}}" > private_key
          chmod 600 private_key
          scp -o StrictHostKeyChecking=no -i private_key deploy-package.zip ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/home/project/example/        
      - name: SSH into Remote Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |   
            cd /home/project/example/
            unzip deploy-package.zip
            #sudo systemctl stop your-app-service  # 停止应用程序服务（如果有）
            #sudo systemctl start your-app-service  # 启动应用程序服务（如果有）
