name: ASP.NET Core 7.0 Example build and deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x  # 更新為.NET 7.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build package
        run: dotnet publish ./src/example -c Release -r linux-x64 --self-contained false -o deploy

      - name: Upload package
        uses: garygrossgarten/github-action-scp@v0.7.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PWD }}
          port: 22
          local: ./deploy/  # 相對於存儲庫根目錄的路徑
          remote: /home/project/example/  # 遠端伺服器上的目標目錄
