name: remote ssh command2
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:		
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: whoami	
