name: ASP.NET Core 7.0 Example build and deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # 添加workflow_dispatch事件以手動觸發

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build package
        run: |
          cd github_actions
          dotnet build --configuration Release --no-restore
          dotnet publish -c Release -r linux-x64 --self-contained false -o deploy                        
      - name: Create Deployment Package
        run: zip -r deploy-package.zip /home/runner/work/github_actions/github_actions/github_actions/deploy/

      - name: Debug Info
        run: |
          pwd
          ls -l
  
      #- name: Upload to Remote Server
      #  run: scp -i ${{ secrets.SSH_PRIVATE_KEY }} deploy-package.zip ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/home/project/example/          
